### PR TITLE
Added EPSG3112

### PR DESCRIPTION
**Pull request by wired00**
- Added EPSG3112/GDA94 
- Added test to Proj4phpTest
- Some format tidying of Proj4phpTest

### CODE REVIEW

**Comment by wired00** [comment]
I'm not sure why travis is complaining with `Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /home/travis/build/proj4php/proj4php/test/CommonTest.php on line 10`. Tests working perfectly locally

**Comment by julien2512** [comment]
It seems there were some changes on PHP 7.

**Comment by julien2512** [comment]
https://www.google.fr/url?sa=t&source=web&rct=j&url=http://stackoverflow.com/questions/6065730/why-fatal-error-class-phpunit-framework-testcase-not-found-in&ved=0ahUKEwi9ydqLl8_TAhUGBBoKHVvYALkQFggfMAA&usg=AFQjCNELct-usDPJpwCMz880FWEA1Ei-Mw&sig2=eVzaN6lnfrBdtfMb_gZ75A

**Comment by wired00** [comment]
Is this an issue your experiencing yourself also? If so, it seems as though travis is not caching composer files correctly. or travis needs to be forced to use php5.7 instead of 7?

I tried this fix, but did not help: http://stackoverflow.com/questions/42811164/class-phpunit-framework-testcase-not-found/42828632

**Comment by julien2512** [comment]
> https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0
> 
> PHPUnit's units of code are now namespaced. For instance, PHPUnit_Framework_TestCase is now PHPUnit\Framework\TestCase 

I am trying to get the code backward compatible.

Your code will be a good starting point !

> if (!class_exists('\PHPUnit\Framework\TestCase') &&
>     class_exists('\PHPUnit_Framework_TestCase')) {
>     class_alias('\PHPUnit_Framework_TestCase', '\PHPUnit\Framework\TestCase');
> }

Eventhough I don't know why !class_exists then class_alias works for Robson & Joao Gilberto !

===> Let's try some fixes !

**Comment by julien2512** [comment]
That one works :

> if (!class_exists('\PHPUnit_Framework_TestCase') && class_exists('\PHPUnit\Framework\TestCase')) {
>     class_alias('\PHPUnit\Framework\TestCase', '\PHPUnit_Framework_TestCase');
> }

I am going to push it on master. We will be able to update & push your branch after that.

**Comment by julien2512** [comment]
The master is up to date ! Thank you for your report.

**Comment by wired00** [comment]
Fantastic @julien2512 I'll try again when I get a spare moment today!

**Comment by wired00** [comment]
Ok thats ready to merge, all travis tests passing.

Also, would you mind if i went through and just tidied up all the test file formatting?

**Comment by julien2512** [comment]
@wired00 Do whatever you need to !

**Pull request merged**
