### PR TITLE
Various CS and formatting changes.

### PR DESCRIPTION
**Pull request by judgej**
About half the errors highlighted by phpstan have been fixed.

This is a bit of a sprint clean rather than a functional change, just to make it easier for future changes to be implemented. There is still too much JavaScript structural legacy IMO that just gives the wrong impression to this otherwise functionally great package. I would like to fix the remaining 800+ issues raised by phpstan (a static code analyser) before this PR is merged (if acceptable).  I am also tweaking code to PSR-1 and PSR-2 where-ever possible.

### CODE REVIEW

**Comment by julien2512** [comment]
Hi @judgej 
   You can tell me when you need me to review your code.
Regards,

**Comment by judgej** [comment]
Will do, thanks.


Sent from my Samsung device

-------- Original message --------

**Comment by judgej** [comment]
@julien2512 I've done all the stuff I intended to do for this PR:

* Some unimportant PSR-1/2 code formatting.
* Defining properties on all objects where they are referenced by the code, They do not all have descriptions; very  few have.
* Updated some tests that relied on properties being declared on-the-fly.
* Fixed a few typo bugs that I found on the way. Not many though.

There is still an issue with some of the tests, and I have put in some conditional checks for a whole category of tests that were failing (all involving properties that were not null, but the tests were expecting them to be null). I *believe* it is the tests that were wrong, looking at internal calculations in properties, but I cannot be sure.

The main aim of this was to being able to see a little more clearly how the code hangs together and where the relationships are between items of data. There are many global properties, and many are freely shared between multiple nested objects, so it can be very difficult to test the code as most of the code has side-effects that change data widely across the library. The original JavaScript took the same approach, *but* scoping rules for that are very different, so that approach was a lot more appropriate.

So - please review. Please ask if you have any questions about *why*, and please shout if you totally disagree with anything in this PR, either functionally or stylistically.

**Comment by julien2512** [comment]
@judgej I will check it next week. I am a little busy right now.

**Comment by judgej** [comment]
After the formatting, I understand how the code works a lot more now. It has allowed me to go much more off-piste in this branch:

https://github.com/academe/proj4php-1/tree/parsers

What I have there is separate classes for [non-projected] Geodetic and Geocentric points. They are driven by the Datum and Ellipsoid classes. All these objects are value-objects, so there are no public properties, no instances of one object poking around in the properties of another object. The points can be freely converted between each other, and the datums can be shifted easily.

The next stage will be to create the projected point, which I suspect will end up being an abstract class with different implementations making up the different types of coordinate systems. A coordinate system will be a projection (which will be one of half a dozen types - spherical, merc, transverse merc, conical etc), and some parameters that define it. A coordinate system will then be able to process only specific types of coordinates, e.g. UTM will support northing/easting/grid codes/latitude bands, OSGB will support easting/northing/grid reference, etc. This bit is more complicated for me to think through, but I think I'm getting there.

As well as these being value objects (a departure from what we have) the objects also do not make any reference to the language used to define the coordinate systems. That will be dealt with entirely in another layer, so the objects created will have no idea whether they came from Proj4 codes, WKT files, or were just created on-the-fly hard-coded in an application. The parsing of the definitions may even be better as a separate package altogether. That's very tempting.

I've not documented this yet, but there are examples in the tests to show how these objects can be created and datum shifted and converted.

Not sure where the end point is for this, and I suspect it will be far too different from the current package to be a simple one-for-one replacement. I can keep it in the branch for now and put some examples together, and you can see if there is anything of use in it.

**Comment by julien2512** [comment]
Hi Jason,

I am not done with your previous Pull Request already !

If any of jour thoughts match or will the actual proj4 road map design, it
is on the good way.
Like using a separate builder for WKT and stuff. But for now we do not
provide the grid support. I do not know if a separate builder could help on
it.

Regards

**Comment by julien2512** [comment]
Alright @judgej, now I am done with it ! It was a so large review !

**Comment by judgej** [comment]
Thanks. Hopefully it has not broken anything, but I'm here if a quick fix is needed.

In my separate branch I have been playing with a projection conversion, with some same code here:

https://github.com/academe/proj4php-1/tree/parsers#new-developments

These objects are instantiated with raw data for now (no Proj4 or WKT or XML parsing) but it hopefully shows where I am trying to go with the objects. The sample converts a geodetic coordinate to an LCC projected XY, and then back again. The class all implement value objects, so no object is messing with the properties of any other object; they simply can't.

**Pull request merged**
