### PR TITLE
The definition of EPSG:28992 is wrong. For some reason there has been…

### PR DESCRIPTION
**Pull request by bbrala**
… an error in getting the definition out there, see https://oegeo.wordpress.com/2008/05/20/note-to-self-the-one-and-only-rd-projection-string/ . This PR corrects that.

### CODE REVIEW

**Comment by julien2512** [comment]
You are welcome !

**Comment by julien2512** [comment]
@bbrala  I am going to pull request it to proj4 and https://epsg.io/28992

**Comment by bbrala** [comment]
Ok cool, thanks for merging. I've run into this issue quite a few times with different software suits. Silly dutchies. :)

**Comment by julien2512** [comment]
Hi @bbrala 

We will need to study your request a bit more to understand why (as Roger Lott says) the CRS are not taken into account during the transformation.

I shall let a branch for your pull request till we get it, and refresh the master, ok ?

**Comment by bbrala** [comment]
Yeah that is fine. I started the discussion by messaging someone I know at osgeo nl and I'm mostly glad there will come a real fix after all these years :)

**Comment by julien2512** [comment]
@bbrala here is the branch merging your pull request : 
https://github.com/proj4php/proj4php/tree/fix-epsg28992

The master do not implement it any more for now (revert pull request).

**Comment by bbrala** [comment]
Yeah no problem thanks :)

**Pull request merged**
