### PR TITLE
Inline projections

### PR DESCRIPTION
**Pull request by nickolanack**
add us survey ft wkt str detection

### CODE REVIEW

**Comment by julien2512** [comment]
I was not possible to merge the scrapper because of the url call (it won't pass travis, and it is far too long).

Even though, that's still be a good idea. Proj4js project uses a local file (in json format) with all the ogc wkt definitions. Is it possible to adapt your code in that way ?

**Comment by nickolanack** [comment]
i didn't even mean to include that

**Comment by nickolanack** [comment]
I've already scraped, and created a test file with about 4000 projections, I'm testing pairs of proj4 and ogcwkt codes to make sure that internally they load the same parameters to the projCode class. 

I've discovered quite a few issues already.

**Comment by nickolanack** [comment]
my goal is to ensure that the wkt parsing is compatible with proj4 definitions, but I'm not worring about testing any point transformations at all

**Comment by nickolanack** [comment]
at any rate, when finished, I'll just commit the codes.json file, and comment out the scaper

**Comment by julien2512** [comment]
You're awesome !

**Comment by julien2512** [comment]
@nickolanack  Well, I found it again, but now, I can push your Scrapper as he do not use url anymore.

**Comment by julien2512** [comment]
thanks.

**Pull request merged**
