### PR TITLE
added missing transcode to wgs if not in source or destination

### PR DESCRIPTION
**Pull request by nickolanack**
added unit test
please make sure that this makes sense - it should address the issue recently reported by @surbinati  

Conversion from EPSG 900913 to EPSG 3003 seems wrong #37

### CODE REVIEW

**Comment by nickolanack** [comment]
transform should add a 2 phase source->WGS84->dest if neither source or destination  project is actually WGS84

**Comment by nickolanack** [comment]
also i tried to compare arrays with precision in my unit test - not even sure if that is possible...?

**Comment by julien2512** [comment]
The issue seems to wake up since I put Travis on proj4php5.2. It was on old one.

As Travis say it's working, I do not read your code. But I will now !

**Comment by julien2512** [comment]
Indeed, the transform method is meant to do the same thing : transform to lonlat then to the dest projection.

**Comment by julien2512** [comment]
That's forward and inverse method, implemented by projection class.

So to say tmerc and merc do not implement them the good way ?

**Comment by julien2512** [comment]
I am working on the reverse test. This is the debug output with your proposal
`
transform point 1508344.3777571,5032839.2985009
from EPSG:3003 to GOOGLE

transform point 1508344.3777571,5032839.2985009
from EPSG:3003 to WGS84
convert to_meter => 1508344.3777571,5032839.2985009
inverse => 0.15894194724588,0.7932203722357
geodetic_to_geocentric(0.15894194724588,0.7932203722357)
geocentric_to_wgs84(4425942.0909071,709452.12834447)
geocentric_to_geodetic(4425719.883424,709388.7720397)
datum_transform => 0.15893583683863,0.79323205345738
convert to longlat => 9.1063526642335,45.448848837603
Transform result 9.1063526642335 45.448848837603

convert to longlat => 0.15893583683863,0.79323205345738
datum_transform => 0.15893583683863,0.79323205345738
convert to_meter => 1013714.5415664,5692462.5127437
Transform result 1013714.5415664 5692462.5127437
`

And without :
`
transform point 1508344.3777571,5032839.2985009
from EPSG:3003 to GOOGLE
convert to_meter => 1508344.3777571,5032839.2985009
inverse => 0.15894194724588,0.7932203722357
datum_transform => 0.15894194724588,0.7932203722357
convert to_meter => 1013753.514581,5692356.312983
Transform result 1013753.514581 5692356.312983
`

We're just 150m away.

**Comment by julien2512** [comment]
As GOOGLE is a WGS84 like, it seems that inverse method is enough to transform the point.

**Comment by julien2512** [comment]
Look at this request :
`
http://spatialreference.org/projection/?json={%22type%22%3A%22Feature%22%2C%20%22geometry%22%3A{%22type%22%3A%22Point%22%2C%20%22coordinates%22%3A[1508344.3777571%2C%205032839.2985009]}%2C%22properties%22%3A{}}&inref=EPSG:3003&outref=sr-org:7483&callback=project_out
`

1508344.3777571,5032839.2985009  in EPSG:3003
mean 
1013753.514581, 5692356.3133690003 in sr-org:7483

and this is the original proj4php answer for "GOOGLE" projection (also known as sr-org 7483).

I guess our result was right.

What do you think of ?

**Comment by nickolanack** [comment]
the problem (in proj4php) is not with tranforming EPSG:3003 => Google , the problem is with transforming:
'+proj=tmerc +lat_0=0 +lon_0=9 +k=0.9996 +x_0=1500000 +y_0=0 +ellps=intl +towgs84=-104.1,-49.1,-9.9,0.971,-2.917,0.714,-11.68 +units=m +no_defs' => Google

**Comment by nickolanack** [comment]
I should not have called it EPSG:3003 in the unit test, I do not know what it is. but I believe it is a valid projection

**Comment by julien2512** [comment]
That's it.

So you mean our code do not use 
`+towgs84=-104.1,-49.1,-9.9,0.971,-2.917,0.714,-11.68`
properly.

**Comment by nickolanack** [comment]
yes

**Comment by nickolanack** [comment]
I think the second step is neccesary becuase proj4php does not transform datums if both projections are geodetic

**Comment by nickolanack** [comment]
the step => toWGS84 => is essentially geodetic_to_geodetic

**Comment by julien2512** [comment]
Proj4 documentation says +towgs84 describes a datum shift.

**Comment by julien2512** [comment]
OK I get you. 
When you force WGS84 transform, a datum shift is done, but when you use +towgs84 only it seems not because it is geodetic_to_geodetic and not geodetic_to_wgs84.

**Comment by nickolanack** [comment]
yes!

**Comment by nickolanack** [comment]
inverse => 0.15894194724588,0.7932203722357
geodetic_to_geocentric(0.15894194724588,0.7932203722357)
geocentric_to_wgs84(4425942.0909071,709452.12834447)
geocentric_to_geodetic(4425719.883424,709388.7720397)
datum_transform => 0.15893583683863,0.79323205345738 <- changed



inverse => 0.15894194724588,0.7932203722357
datum_transform => 0.15894194724588,0.7932203722357 <- no change

**Comment by nickolanack** [comment]
if it was not the case, adding the step to wgs84 should only cause rounding issues.

**Comment by julien2512** [comment]
May the datum_type needs to be set during the parsing of proj4 def including +towgs.

**Comment by nickolanack** [comment]
it is being parsed, it is just not being used

**Comment by julien2512** [comment]
There is : 
`if ($source->datum_type == Common::PJD_NODATUM || $dest->datum_type == Common::PJD_NODATUM) {
            return $point;
        }`

and 

`if ($source->datum_type == Common::PJD_3PARAM || $source->datum_type == Common::PJD_7PARAM) {`

...

**Comment by nickolanack** [comment]
}

	/**
	 * Why not call this class "equals()"? Compare functions tend to return more
	 * than just a true/false. if ($datum1->equals($datum2)) ...
	 *
	 * @param type $dest
	 * @return boolean Returns TRUE if the two datums match, otherwise FALSE.
	 * @throws type
	 */
	public function compare_datums(Datum $dest) {

		if ($this->datum_type != $dest->datum_type) {
			// Datums are not equal
			return false;
		} elseif ($this->a != $dest->a || abs($this->es - $dest->es) > 0.000000000050) {

			// The tolerence for es is to ensure that GRS80 and WGS84

**Comment by julien2512** [comment]
I guess compare_datums is not really used.

**Comment by julien2512** [comment]
in Proj.php,
`case "towgs84":
                    $this->datum_params = explode( ",", $paramVal);
                    break;
`

do not set datum_type.

**Comment by julien2512** [comment]
You mean by now, compare_datums returns true for our unit test and never shift datum ?

**Comment by nickolanack** [comment]
Yes I think that is essentially what is happening - although there is no geodetic_to_geodetic method anyway (which we could implement) but using WGS84 as an intermediate step essentially calling

dst=gecentric_to_geodetic(geodetic_to_geocentric(src)), 
and we get the shift

**Comment by julien2512** [comment]
Eventhough I set datum_type for 3003, it actually fails on 
`if ($source->datum_type == Common::PJD_NODATUM || $dest->datum_type == Common::PJD_NODATUM) {`
because GOOGLE do not have a datum.

**Comment by nickolanack** [comment]
ha, I tried that earlier to...

**Comment by julien2512** [comment]
With a &&, I got the good X, but a bad Y :
`
1013714.5415664 5661983.5468984
`

**Comment by nickolanack** [comment]
proj4php line 615 - might be where we need to look
'''
  if ($source->es != $dest->es || $source->a != $dest->a
            || $source->datum_type == Common::PJD_3PARAM
            || $source->datum_type == Common::PJD_7PARAM
            || $dest->datum_type == Common::PJD_3PARAM
            || $dest->datum_type == Common::PJD_7PARAM
        ) {
            // Convert to geocentric coordinates.
            $source->geodetic_to_geocentric($point);

            // CHECK_RETURN;
            // Convert between datums
            if ($source->datum_type == Common::PJD_3PARAM || $source->datum_type == Common::PJD_7PARAM) {
                $source->geocentric_to_wgs84($point);
                // CHECK_RETURN;
            }

            if ($dest->datum_type == Common::PJD_3PARAM || $dest->datum_type == Common::PJD_7PARAM) {
                $dest->geocentric_from_wgs84($point);
                // CHECK_RETURN;
            }

            // Convert back to geodetic coordinates
            $dest->geocentric_to_geodetic($point);
            // CHECK_RETURN;
        }

**Comment by julien2512** [comment]
I do not know why the debug log tell the variables are 
`Dx=-104.1
Dy=-49.1
Dz=-9.9
Rx=4.7075408435736E-6
Ry=-1.4142015077965E-5
Rz=3.4615696831221E-6
M=0.99998832`
instead of 
`+towgs84=-104.1,-49.1,-9.9,0.971,-2.917,0.714,-11.68`

that do not make sense.

**Comment by nickolanack** [comment]
the last few get changed a little

**Comment by nickolanack** [comment]
ill find the line

**Comment by nickolanack** [comment]
Datum.php line 54

**Comment by julien2512** [comment]
grep datum_params src/*  ?

**Comment by nickolanack** [comment]
scale change in parts per million.

**Comment by julien2512** [comment]
The code appears not so bad (with && rather than ||).

We're back at the beginning (or near by !). When we use  WGS84  datum shifts,
we get the good result, and when we use
+towgs84=-104.1,-49.1,-9.9,0.971,-2.917,0.714,-11.68
we are far away.

**Comment by nickolanack** [comment]
good work!

**Pull request merged**
